-- MySQL Script generated by MySQL Workbench
-- Thu Sep 24 03:01:25 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema soft1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `soft1` ;

-- -----------------------------------------------------
-- Schema soft1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `soft1` DEFAULT CHARACTER SET utf8 ;
USE `soft1` ;

-- -----------------------------------------------------
-- Table `soft1`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `soft1`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`rol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(15) NOT NULL,
  `descripcion` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soft1`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`usuario` (
  `id` INT NOT NULL,
  `rol` INT NOT NULL,
  `tipo_Documento` VARCHAR(25) NOT NULL,
  `nombre1` VARCHAR(20) NOT NULL,
  `nombre2` VARCHAR(20) NULL DEFAULT NULL,
  `apellido1` VARCHAR(20) NOT NULL,
  `apellido2` VARCHAR(20) NULL DEFAULT NULL,
  `direccion` VARCHAR(60) NOT NULL,
  `telefono` INT NOT NULL,
  `correo` VARCHAR(70) NOT NULL,
  `contraseña` VARCHAR(15) NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_usuario_rol1`
    FOREIGN KEY (`rol`)
    REFERENCES `soft1`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_usuario_rol1_idx` ON `soft1`.`usuario` (`rol` ASC);


-- -----------------------------------------------------
-- Table `soft1`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`administrador` (
  `id` INT NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_administrador_usuario1`
    FOREIGN KEY (`id`)
    REFERENCES `soft1`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soft1`.`asesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`asesor` (
  `id` INT NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_asesor_usuario1`
    FOREIGN KEY (`id`)
    REFERENCES `soft1`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_asesor_usuario1_idx1` ON `soft1`.`asesor` (`id` ASC);


-- -----------------------------------------------------
-- Table `soft1`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`cliente` (
  `id` INT NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cliente_usuario1`
    FOREIGN KEY (`id`)
    REFERENCES `soft1`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_cliente_usuario1_idx` ON `soft1`.`cliente` (`id` ASC);


-- -----------------------------------------------------
-- Table `soft1`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`pedido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cliente` INT NOT NULL,
  `nombre_Cliente` VARCHAR(75) NOT NULL,
  `fecha` DATE NOT NULL,
  `direccion` VARCHAR(60) NOT NULL,
  `fecha_Entrega` DATE NOT NULL,
  `telefono` INT NOT NULL,
  `descripcion_Pedido` VARCHAR(70) NULL DEFAULT NULL,
  `cantidad` INT(11) NOT NULL,
  `valor_Unitario` DOUBLE NOT NULL,
  `valor_iva` DOUBLE NOT NULL,
  `valor_Total` DOUBLE NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_pedido_cliente1`
    FOREIGN KEY (`cliente`)
    REFERENCES `soft1`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_pedido_cliente1_idx` ON `soft1`.`pedido` (`cliente` ASC);


-- -----------------------------------------------------
-- Table `soft1`.`despacho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`despacho` (
  `id` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `pedido` INT NOT NULL,
  `cliente` INT NOT NULL,
  `nombre_Cliente` VARCHAR(75) NOT NULL,
  `direccion_Cliente` VARCHAR(60) NOT NULL,
  `telefono` INT NOT NULL,
  `descripcion_Despacho` VARCHAR(125) NOT NULL,
  `cantidad` INT NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_despacho_pedido1`
    FOREIGN KEY (`pedido`)
    REFERENCES `soft1`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_despacho_cliente1`
    FOREIGN KEY (`cliente`)
    REFERENCES `soft1`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_despacho_pedido1_idx` ON `soft1`.`despacho` (`pedido` ASC);

CREATE INDEX `fk_despacho_cliente1_idx` ON `soft1`.`despacho` (`cliente` ASC);


-- -----------------------------------------------------
-- Table `soft1`.`tipo_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`tipo_pago` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_Tipo_Pago` VARCHAR(45) NOT NULL,
  `descripcion_Tipo_Pago` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soft1`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`factura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pedido` INT NOT NULL,
  `cliente` INT NOT NULL,
  `tipo_Pago` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `valor_Iva` DOUBLE NOT NULL,
  `valor_Total` DOUBLE NULL DEFAULT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_factura_pedido1`
    FOREIGN KEY (`pedido`)
    REFERENCES `soft1`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_tipo_Pago1`
    FOREIGN KEY (`tipo_Pago`)
    REFERENCES `soft1`.`tipo_pago` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_cliente1`
    FOREIGN KEY (`cliente`)
    REFERENCES `soft1`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_factura_tipo_Pago1_idx` ON `soft1`.`factura` (`tipo_Pago` ASC);

CREATE INDEX `fk_factura_pedido1_idx` ON `soft1`.`factura` (`pedido` ASC);

CREATE INDEX `fk_factura_cliente1_idx` ON `soft1`.`factura` (`cliente` ASC);


-- -----------------------------------------------------
-- Table `soft1`.`logistica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`logistica` (
  `id` INT NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_logistica_usuario1`
    FOREIGN KEY (`id`)
    REFERENCES `soft1`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_logistica_usuario1_idx` ON `soft1`.`logistica` (`id` ASC);


-- -----------------------------------------------------
-- Table `soft1`.`solicitud_compra_repuesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`solicitud_compra_repuesto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `logistica` INT NOT NULL,
  `pedido` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `cantidad` INT NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_solicitud_compra_repuestos_logistica1`
    FOREIGN KEY (`logistica`)
    REFERENCES `soft1`.`logistica` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_compra_repuestos_pedido1`
    FOREIGN KEY (`pedido`)
    REFERENCES `soft1`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_solicitud_compra_repuestos_logistica1_idx` ON `soft1`.`solicitud_compra_repuesto` (`logistica` ASC);

CREATE INDEX `fk_solicitud_compra_repuestos_pedido1_idx` ON `soft1`.`solicitud_compra_repuesto` (`pedido` ASC);


-- -----------------------------------------------------
-- Table `soft1`.`vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`vendedor` (
  `id` INT NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_vendedor_usuario1`
    FOREIGN KEY (`id`)
    REFERENCES `soft1`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_vendedor_usuario1_idx` ON `soft1`.`vendedor` (`id` ASC);


-- -----------------------------------------------------
-- Table `soft1`.`orden_compra_repuesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`orden_compra_repuesto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `vendedor` INT NOT NULL,
  `solicitud_Compra_Repuesto` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `cantidad` INT(11) NOT NULL,
  `valor_unitario` DOUBLE NOT NULL,
  `valor_Iva` DOUBLE NOT NULL,
  `valor_Total` DOUBLE NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_orden_Compra_Repuesto_solicitud_Compra_Repuestos1`
    FOREIGN KEY (`solicitud_Compra_Repuesto`)
    REFERENCES `soft1`.`solicitud_compra_repuesto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orden_compra_repuesto_vendedor1`
    FOREIGN KEY (`vendedor`)
    REFERENCES `soft1`.`vendedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_orden_Compra_Repuesto_solicitud_Compra_Repuestos1_idx` ON `soft1`.`orden_compra_repuesto` (`solicitud_Compra_Repuesto` ASC);

CREATE INDEX `fk_orden_compra_repuesto_vendedor1_idx` ON `soft1`.`orden_compra_repuesto` (`vendedor` ASC);


-- -----------------------------------------------------
-- Table `soft1`.`pqrs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`pqrs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cliente` INT NOT NULL,
  `asesor` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `descripcion` VARCHAR(120) NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_pqrs_asesor1`
    FOREIGN KEY (`asesor`)
    REFERENCES `soft1`.`asesor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pqrs_cliente1`
    FOREIGN KEY (`cliente`)
    REFERENCES `soft1`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_pqrs_cliente1_idx` ON `soft1`.`pqrs` (`cliente` ASC);

CREATE INDEX `fk_pqrs_asesor1_idx` ON `soft1`.`pqrs` (`asesor` ASC);


-- -----------------------------------------------------
-- Table `soft1`.`tipo_pqrs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`tipo_pqrs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_PQRS` VARCHAR(25) NOT NULL,
  `descripcion_PQRS` VARCHAR(60) NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soft1`.`pqrs_has_tipo_pqrs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`pqrs_has_tipo_pqrs` (
  `PQRS` INT NOT NULL,
  `tipo_PQRS` INT NOT NULL,
  PRIMARY KEY (`PQRS`, `tipo_PQRS`),
  CONSTRAINT `fk_PQRS_has_tipo_PQRS_PQRS1`
    FOREIGN KEY (`PQRS`)
    REFERENCES `soft1`.`pqrs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PQRS_has_tipo_PQRS_tipo_PQRS1`
    FOREIGN KEY (`tipo_PQRS`)
    REFERENCES `soft1`.`tipo_pqrs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_PQRS_has_tipo_PQRS_tipo_PQRS1_idx` ON `soft1`.`pqrs_has_tipo_pqrs` (`tipo_PQRS` ASC);

CREATE INDEX `fk_PQRS_has_tipo_PQRS_PQRS1_idx` ON `soft1`.`pqrs_has_tipo_pqrs` (`PQRS` ASC);


-- -----------------------------------------------------
-- Table `soft1`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`proveedor` (
  `id` INT NOT NULL,
  `nombre_Proveedor` VARCHAR(60) NOT NULL,
  `direccion_Proveedor` VARCHAR(60) NOT NULL,
  `telefono_Proveedor` INT NOT NULL,
  `correo_Proveedor` VARCHAR(70) NULL DEFAULT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soft1`.`tipo_repuesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`tipo_repuesto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_Tipo_Repuesto` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `soft1`.`repuesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`repuesto` (
  `id` INT NOT NULL,
  `tipo_Repuesto` INT NOT NULL,
  `fecha_Registro_Repuesto` DATE NOT NULL,
  `nombre_Repuesto` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `imagen` LONGBLOB NOT NULL,
  `descripcion_repuesto` VARCHAR(60) NOT NULL,
  `cantidad` INT NOT NULL,
  `valor_Compra` DOUBLE NOT NULL,
  `valor_Venta` DOUBLE NOT NULL,
  `estado` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_repuesto_tipo_Repuesto1`
    FOREIGN KEY (`tipo_Repuesto`)
    REFERENCES `soft1`.`tipo_repuesto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_repuesto_tipo_Repuesto1_idx` ON `soft1`.`repuesto` (`tipo_Repuesto` ASC);


-- -----------------------------------------------------
-- Table `soft1`.`despacho_has_repuesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`despacho_has_repuesto` (
  `despacho` INT NOT NULL,
  `repuesto` INT NOT NULL,
  PRIMARY KEY (`despacho`, `repuesto`),
  CONSTRAINT `fk_repuesto_has_despacho_despacho1`
    FOREIGN KEY (`despacho`)
    REFERENCES `soft1`.`despacho` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_repuesto_has_despacho_repuesto1`
    FOREIGN KEY (`repuesto`)
    REFERENCES `soft1`.`repuesto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_repuesto_has_despacho_despacho1_idx` ON `soft1`.`despacho_has_repuesto` (`despacho` ASC);

CREATE INDEX `fk_repuesto_has_despacho_repuesto1_idx` ON `soft1`.`despacho_has_repuesto` (`repuesto` ASC);


-- -----------------------------------------------------
-- Table `soft1`.`factura_has_repuesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`factura_has_repuesto` (
  `factura` INT NOT NULL,
  `repuesto` INT NOT NULL,
  PRIMARY KEY (`factura`, `repuesto`),
  CONSTRAINT `fk_repuesto_has_factura_factura1`
    FOREIGN KEY (`factura`)
    REFERENCES `soft1`.`factura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_repuesto_has_factura_repuesto1`
    FOREIGN KEY (`repuesto`)
    REFERENCES `soft1`.`repuesto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_repuesto_has_factura_factura1_idx` ON `soft1`.`factura_has_repuesto` (`factura` ASC);

CREATE INDEX `fk_repuesto_has_factura_repuesto1_idx` ON `soft1`.`factura_has_repuesto` (`repuesto` ASC);


-- -----------------------------------------------------
-- Table `soft1`.`pedido_has_repuesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`pedido_has_repuesto` (
  `pedido` INT NOT NULL,
  `repuesto` INT NOT NULL,
  PRIMARY KEY (`pedido`, `repuesto`),
  CONSTRAINT `fk_repuesto_has_pedido_pedido1`
    FOREIGN KEY (`pedido`)
    REFERENCES `soft1`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_repuesto_has_pedido_repuesto1`
    FOREIGN KEY (`repuesto`)
    REFERENCES `soft1`.`repuesto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_repuesto_has_pedido_pedido1_idx` ON `soft1`.`pedido_has_repuesto` (`pedido` ASC);

CREATE INDEX `fk_repuesto_has_pedido_repuesto1_idx` ON `soft1`.`pedido_has_repuesto` (`repuesto` ASC);


-- -----------------------------------------------------
-- Table `soft1`.`repuesto_has_proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`repuesto_has_proveedor` (
  `proveedor` INT NOT NULL,
  `repuesto` INT NOT NULL,
  PRIMARY KEY (`proveedor`, `repuesto`),
  CONSTRAINT `fk_repuesto_has_proveedor_proveedor1`
    FOREIGN KEY (`proveedor`)
    REFERENCES `soft1`.`proveedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_repuesto_has_proveedor_repuesto1`
    FOREIGN KEY (`repuesto`)
    REFERENCES `soft1`.`repuesto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_repuesto_has_proveedor_proveedor1_idx` ON `soft1`.`repuesto_has_proveedor` (`proveedor` ASC);

CREATE INDEX `fk_repuesto_has_proveedor_repuesto1_idx` ON `soft1`.`repuesto_has_proveedor` (`repuesto` ASC);


-- -----------------------------------------------------
-- Table `soft1`.`solicitud_compra_repuestos_has_repuesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soft1`.`solicitud_compra_repuestos_has_repuesto` (
  `solicitud_compra_repuesto` INT NOT NULL,
  `repuesto` INT NOT NULL,
  PRIMARY KEY (`solicitud_compra_repuesto`, `repuesto`),
  CONSTRAINT `fk_repuesto_has_solicitud_compra_repuestos_repuesto1`
    FOREIGN KEY (`repuesto`)
    REFERENCES `soft1`.`repuesto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_repuesto_has_solicitud_compra_repuestos_solicitud_compra_r1`
    FOREIGN KEY (`solicitud_compra_repuesto`)
    REFERENCES `soft1`.`solicitud_compra_repuesto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_repuesto_has_solicitud_compra_repuestos_solicitud_compra_idx` ON `soft1`.`solicitud_compra_repuestos_has_repuesto` (`solicitud_compra_repuesto` ASC);

CREATE INDEX `fk_repuesto_has_solicitud_compra_repuestos_repuesto1_idx` ON `soft1`.`solicitud_compra_repuestos_has_repuesto` (`repuesto` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
